name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    name: Lint and Test Frontend & Backend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20] # You can specify supported Node.js versions

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 3: Run Backend Lint and Tests
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run backend linter
        working-directory: ./backend
        run: npm run lint

      - name: Run backend tests
        working-directory: ./backend
        run: npm test

      # Step 4: Run Frontend Lint and Build
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run frontend linter
        working-directory: ./frontend
        run: npm run lint

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
