name: Lint and Test Frontend & Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js for Frontend
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can adjust this to your Node.js version

      # Step 3: Install dependencies for Frontend
      - name: Install dependencies (Frontend)
        working-directory: ./frontend
        run: |
          npm install

      # Step 4: Run linting for Frontend
      - name: Run linting (Frontend)
        working-directory: ./frontend
        run: |
          npm run lint

      # Step 5: Run tests for Frontend
      - name: Run tests (Frontend)
        working-directory: ./frontend
        run: |
          npm run test

      # Step 6: Set up Node.js for Backend
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can adjust this to your Node.js version

      # Step 7: Install dependencies for Backend
      - name: Install dependencies (Backend)
        working-directory: ./backend
        run: |
          npm install

      # Step 8: Run linting for Backend
      - name: Run linting (Backend)
        working-directory: ./backend
        run: |
          npm run lint

      # Step 9: Run tests for Backend
      - name: Run tests (Backend)
        working-directory: ./backend
        run: |
          npm run test
